### ISSUE TITLE
Enhancement -- Create global constants for values that change each year

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-Script-Team/BZS-FuncLib#191] opened 2016-03-10 20:21 UTC
This came about because of a need to change the income standards in NOTES >> LEP SPONSOR INCOME... Methinks constants that change on a yearly basis should be stored in FuncLib so we have just one place to go to change important constant values rather than changing the values piecemeal.

I have already updated NOTES >> LEP SPONSOR INCOME (so that's one script that will need its constants swapped) but we should probably also identify other scripts with constants that need to be updated on an annual basis.

**Comment by theVKC** [comment] 2016-03-14 14:20
Do you want this, @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment] 2016-03-14 20:30
I would. I'll work on a way to implement this for different household sizes, but I'm confident I can whip something up.

**Comment by theVKC** [comment] 2016-03-21 15:58
@RobertFewins-Kalb: tagging with the April release. Let me know if you need me to change that. :)

**Comment by theVKC** [comment] 2016-04-18 19:18
@RobertFewins-Kalb and @CDPotter:

I think #203 might be a duplicate of this. Let's add a "cutoff date list" to this issue. I'll close the other issue.

**Comment by CDPotter** [comment] 2016-04-18 19:25
POLI/TEMP! TE19.132 contains cutoff date information. Would be nifty if we could just have the function read from POLI TEMP each time =P this is super helpful though!

**Comment by theVKC** [comment] 2016-04-25 22:19
@RobertFewins-Kalb, can I get an update on this one?

**Comment by RobertFewins-Kalb** [comment] 2016-04-26 13:11
None progress at this point

**Comment by theVKC** [comment] 2016-04-26 16:17
It's tagged with the May release, and enhancements are due by May 13. Do you think you'll be able to get it done by then?

**Comment by RobertFewins-Kalb** [comment] 2016-04-26 16:34
Yes. I will be able to have something by then

**Comment by theVKC** [comment] 2016-04-27 15:16
Thank you!

**Comment by RobertFewins-Kalb** [comment] 2016-05-05 15:53
How do we feel about this warning box when we forget to update the global constants?

![image](https://cloud.githubusercontent.com/assets/7842016/15048538/a65a6dd8-12af-11e6-9e5d-251527b5dc41.png)

**Comment by CDPotter** [comment] 2016-05-05 16:08
Seems like a good backup reminder to me.

**Comment by theVKC** [comment] 2016-05-05 16:16
Agreed.

**Comment by RobertFewins-Kalb** [comment] 2016-05-05 16:20
Then I am ready to submit three new functions to FuncLib for the categorically eligible income limits, the gross income limits and the net income limits. To use each function, you could use the _HH_member_custom_dialog_ function and pass the ubound of the array +1 for _household_size_ and the function returns the income limit for that household size.

The values for the income tests and the _valid_through_date_ need to be updated once per year

**Comment by theVKC** [comment] 2016-05-05 16:22
Should we declare `household_size + 1` as a constant and pull it out to be used elsewhere in scripts?

**Comment by RobertFewins-Kalb** [comment] 2016-05-05 16:26
I think that's certainly the easiest way to use the function, but I don't want to pigeon-hole script writers to using it. I could imagine a scenario where a script is checking EATS and determines the hh size that way. In that case `household_size = household_size + 1` would be a valid way to put data into the function.

**Comment by theVKC** [comment] 2016-05-05 16:29
Good point.

I'm wondering if this isn't a good target for standardization? Seems like we're going to use it a lot for lots of scripts. Also, it varies by program, so I could see using different variables simultaneously (`SNAP_HH_size <> MFIP_HH_size`).

In any case, I think we should use your method now, and consider this in the near future with Bowie considerations.

**Comment by RobertFewins-Kalb** [comment] 2016-05-05 16:31
I left MFIP & DWP alone. I saw the income limit business in CM but I thought it best to leave that to family cash peeps as `robert(MFIP).program_knowledge < 10`

**Closed** 2016-05-09 18:37 UTC
Labels: constants, enhancement
