### ISSUE TITLE
Create a function for cutoff dates

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/BZS-FuncLib#203] opened 2016-04-18 14:21 UTC
We should create a function to calculate cutoff dates. 

Possible solutions include:

next_cutoff_date could be a variable which determines itself based on a cutoff list on FuncLib. That's my vote. Maybe current_mo_cutoff_date and next_mo_cutoff_date, and we insert all known cutoff dates and update monthly/bimonthly. Thoughts?

Function cutoff_date_calc(footer_month, cutoff_date)
if footer_month = "04" THEN cutoff_date = "04/20/16"
ETC
(to do this method we would need a list of cutoff dates for the foreseeable future and make sure to update when we run out.)

Once this is completed we can finish up https://github.com/MN-Script-Team/DHS-MAXIS-Scripts/issues/2123 which will contain a list of script that can benefit from cutoff dates calculators. 

end function

**Comment by theVKC** [comment] 2016-04-18 16:41
Do you want this one, @CDPotter?

**Comment by CDPotter** [comment] 2016-04-18 16:43
Sure, would you be able to get a list of cutoffs for 2016?

**Comment by theVKC** [comment] 2016-04-18 16:44
I just have the same one that's on SIR.

**Comment by CDPotter** [comment] 2016-04-18 16:46
So just the current/future months hm? Is there anyone you could contact to get a full list? I'm envisioning a "doomsday" situation where the constant doesn't get updated in time or something and scripts start breaking due to bad dates.

**Comment by theVKC** [comment] 2016-04-18 16:59
That's why we haven't done this in the past. I'll contact some folks and we'll hope for the best.

**Comment by theVKC** [comment] 2016-04-18 18:03
Cool! Go POLI/TEMP! TE19.132

**Comment by theVKC** [comment] 2016-04-18 19:20
I'm calling this issue a duplicate of #191. @CDPotter, I'm closing this. Can you add any comments on this to #191? Thanks!

**Closed by theVKC** 2016-04-18 19:20 UTC
Labels: constants, duplicate, enhancement, new function
